test_core and test_tuple are working need to do lots of cleanup
4 in test_core failing:
test_for_iv[34359738368-34359738388-1] - AssertionError: assert tensor(0, device='cuda:0') == 687194767550
 +  where 687194767550 = sum(range(34359738368, 34359738388))
 +    where range(34359738368, 34359738388) = range(34359738368, 34359738388, 1)
FAILED python/test/unit/language/test_core.py::test_for_iv[34359738368-34359738388-2] - AssertionError: assert tensor(0, device='cuda:0') == 343597383770
 +  where 343597383770 = sum(range(34359738368, 34359738388, 2))
 +    where range(34359738368, 34359738388, 2) = range(34359738368, 34359738388, 2)
FAILED python/test/unit/language/test_core.py::test_for_iv[34359738368-34359738388-3] - AssertionError: assert tensor(0, device='cuda:0') == 240518168639
 +  where 240518168639 = sum(range(34359738368, 34359738388, 3))
 +    where range(34359738368, 34359738388, 3) = range(34359738368, 34359738388, 3)
FAILED python/test/unit/language/test_core.py::test_gather[src_shape2-indices_shape2-0]